version: '3.8'

services:
  # model-server:
  #   build:
  #     context: ./model_server
  #     dockerfile: Dockerfile
  #   container_name: fish_detector_model_server
  #   ports:
  #     - "8000:8000"
  #   restart: unless-stopped
  #   volumes:
  #     - ./model:/app/model:ro
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
  #     interval: 5s
  #     timeout: 3s
  #     retries: 5

  batch-labeling:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      model-server:
        condition: service_healthy
    volumes:
      - "./input_images:/workspace/input_images:ro"
      - "./aug_images:/workspace/aug_images"
      - "./inference_results:/workspace/inference_results"
      - "./model:/workspace/model:ro"
    command: ["python", "main.py"]
