# version: '3.8'

services:
  model-server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: fish_detector_model_server_standalone
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./model:/app/model
      - ../results:/app/results
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 5s
      timeout: 3s
      retries: 5